/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pos.products;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.Box;
import pos.MainWindow;

/**
 *
 * @author Eric, Tako, Jordy, Ahmet en Duraid
 */
public class ProductList extends javax.swing.JPanel {
     private final MainWindow mainWindow;
     private final Category category;
   
private void addProducts() {
    List<Product> prods = Product.findByCategory(category, mainWindow.getDbManager());
   //oud List<Product> prods = Product.findAll(mainWindow.getDbManager());
    
    for (final Product product : prods) {
        ProductItem productItem = new ProductItem(product);
        productItem.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mainWindow.showPanel(new ProductDetails(mainWindow, product));
            }
        });
        products.add(productItem);
    }
    products.add(Box.createVerticalGlue());
}
     
     
    /**
     * Creates new form ProductList
     * @param mainWindow
     * @param category
     */
    public ProductList(MainWindow mainWindow, Category category) {
        this.mainWindow = mainWindow;
        this.category = category;
        initComponents();
        addProducts();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basket = new pos.orders.BasketPanel(mainWindow);
        productsScrollPane = new javax.swing.JScrollPane();
        products = new javax.swing.JPanel();

        products.setLayout(new javax.swing.BoxLayout(products, javax.swing.BoxLayout.Y_AXIS));
        productsScrollPane.setViewportView(products);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(basket, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(basket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(92, 92, 92))
                    .addComponent(productsScrollPane))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pos.orders.BasketPanel basket;
    private javax.swing.JPanel products;
    private javax.swing.JScrollPane productsScrollPane;
    // End of variables declaration//GEN-END:variables
}
